### ISSUE TITLE
Lidar Point Cloud Upside Down

### ISSUE THREAD

**Issue by Unknown-Student** [mich1342/ros2_laser_scan_merger#9]
I have a quite particular issue. 
On my robot there are two lidar scanners: 

- at the front, mounted upside down
- at the back mounted upright

I manages to merged them with this package, but the front laser is upside down. I already tried to adjust the links to which the lasers are attached with no success. 

![IMG_20231201_150113_492](https://github.com/mich1342/ros2_laser_scan_merger/assets/121166053/4075533c-8cbd-4714-a96b-5c1f46957190)

In the picture above the red point are the ones from the merged point cloud the green points are the ones from the lidar scanner with the link transformations applied, and where the objects should be. 

Is there any way to flip the merged point cloud for the merged cloud? 

If you need any more information, please let me know.

**Comment by mich1342** [comment]
Hi @Unknown-Student,

Thank you for your interest in using this package. Unfortunately adjusting the link between two lidars could not solve the problem. To support your use cases, I need to add additional features to flip the Lidars Reading manually. I might need 1-2 weeks to do that due to my current work load. Thank you and hopefully the timeline fits your needs.

Best Regards

Michael

**Comment by Unknown-Student** [comment]
Hello Michael,

Thank you for the fast response.

1-2 weeks should be okay, and I think this feature would be a great addition to the project.

Best Regards,
Unknown Student

**Comment by Unknown-Student** [comment]
Hi @mich1342,

I wrote a short script that just flipped the incoming message from the laserscanner before giving it to the merger.

```python
#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import LaserScan

from rclpy.qos import QoSDurabilityPolicy, QoSHistoryPolicy, QoSReliabilityPolicy
from rclpy.qos import QoSProfile

class FlipLaser(Node):
    def __init__(self):
        super().__init__('flip_laser')

        qos_profile = QoSProfile(depth=10)
        qos_profile.reliability = QoSReliabilityPolicy.BEST_EFFORT
        qos_profile.durability = QoSDurabilityPolicy.VOLATILE
        

        self.laser_sub = self.create_subscription(LaserScan,"/lidar_3/scan",self.callback,qos_profile)
        self.laser_pub = self.create_publisher(LaserScan, "/lidar_1/scan", 10)

    def callback(self,data):
        print(data.ranges)
        msg = LaserScan()

        msg.header = data.header
        msg.angle_max = data.angle_max
        msg.angle_min = data.angle_min
        msg.angle_increment = data.angle_increment
        msg.time_increment = data.time_increment
        msg.scan_time = data.scan_time
        msg.range_min = data.range_min
        msg.range_max = data.range_max

        msg.ranges = FlipLaser.reverse(data.ranges)

        msg.intensities = FlipLaser.reverse(data.intensities)
        self.laser_pub.publish(msg)
        print("FLIPED")
        print(data.ranges)
    
    def reverse(list):
        list.reverse()
        return list

    def main(args=None):
    rclpy.init(args=args)
    node = FlipLaser()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

    if __name__ == "__main__":
         main()

``` 

I hope this helps.

Best Regards

PS: I'm quite new to the github merging and pr things. Sorry if this is not the usual way of contributing to repos.

**Comment by mich1342** [comment]
Hi @Unknown-Student,
Thank you for your help. Will for sure add the functionalities to tbe code. I am sorry I have not got the time to do it right now. 

best regards

Michael

**Comment by mich1342** [comment]
hi @Unknown-Student ,

Sorry for the late reply. Just got the chances to update the code. I have added the flip1 and flip2 parameters to flip the Lidars accordingly. Could you help to verify it? I have not got access to my hardware until mid Feb 2024. I ends up playing with the index of the array accessed when calculating the x-y from the laserscan data instead of to full reverse to the array as shown below

![image](https://github.com/mich1342/ros2_laser_scan_merger/assets/48148450/814ab876-324e-4643-b710-eab2d9b4ae68)

It should works the same. Thank you 

Best Regards

Michael Jonathan

**Comment by mich1342** [comment]
![image](https://github.com/mich1342/ros2_laser_scan_merger/assets/48148450/11c651f4-29ad-4075-8832-e8d777403f84)
My bad, forgot to add the -1 for the size

**Comment by Unknown-Student** [comment]
Thank you @mich1342,
I currently do not have access to any hardware either, and I don't know when I will have it again.
Thank you for implementing this feature.
I will test it out as soon as I can. 
Best Regards

**Comment by mich1342** [comment]
Will close this issues, Have checked it works in my setup. Thank you

**Comment by mich1342** [comment]
Tested working
